### PR TITLE
Port `psocake` to S3DF.

### PR DESCRIPTION
**Pull request by carbonscott**
Need the following files (let's call it `setup-sh`) to run crystfel.

```
CFDIR=/sdf/group/lcls/ds/tools/crystfel/0.10.2

export CLIBD=/sdf/group/lcls/ds/tools/ccp4-8.0/lib/data
export CINCL=/sdf/group/lcls/ds/tools/ccp4-8.0/include
export CCP4_SCR=/tmp

export PATH=${CFDIR} /bin:$PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${CFDIR}/lib/pkgconfig
export LD_RUN_PATH=$LD_RUN_PATH: ${CFDIR} /lib
```

Moreover, run the following wrapper function to use `psocake` on s3df.

```
function psocake3.start ()
{
    echo 'Loading psocake3...'
    export PATH="/sdf/home/c/cwang31/codes/psocake/app:$PATH"
    export PYTHONPATH="/sdf/home/c/cwang31/codes/psocake:$PYTHONPATH"

    # CrystFEL
    source "PATH TO THE ABOVE setup-sh FILE"   # <--- Use a real path to the setup-sh file

    # CCP4
    source /sdf/group/lcls/ds/tools/ccp4-8.0/bin/ccp4.setup-sh

    # XDS
    export PATH=/sdf/group/lcls/ds/tools/XDS-INTEL64_Linux_x86_64:$PATH
}
```

### CODE REVIEW

**Comment by carbonscott** [comment]
I don't think it should be merged to the main branch yet, but this PR highlights places that need changes to make `psocake` run on s3df.

**Comment by carbonscott** [comment]
One more thing to point out: the version of crystfel on s3df requires one extra key-value pair as annotated in the  example `geom` file below.  Unfortunately, the program won't run without specifying it explicitly.

```
clen =  /LCLS/detector_1/EncoderValue
photon_energy = /LCLS/photon_energy_eV
adu_per_eV = 0.1

data = /entry_1/data_1/data

dim0 = %
dim1 = ss
dim2 = fs

mask = /entry_1/data_1/mask
mask_file = ./mfxlx5520/cwang31/psocake/r0100/mfxlx5520_0100.cxi
mask_good = 0x0000
mask_bad = 0xffff

p0a0/fs = +0.000000x +1.000000y
p0a0/ss = -1.000000x +0.000000y
p0a0/res = 11235.955
p0a0/corner_x = 959.631100
p0a0/corner_y = -963.411167
p0a0/coffset = -0.16602160000000005
p0a0/min_fs = 0
p0a0/max_fs = 1919
p0a0/min_ss = 0
p0a0/max_ss = 1919
p0a0/no_index = 0

; __/ NEW key-value pair \__
; https://www.desy.de/~twhite/crystfel/manual-crystfel_geometry.html
peak_list = /entry_1/result_1
```

**Comment by chuckie82** [comment]
Notes:

Add to .bashrc
# psana1
source /sdf/group/lcls/ds/ana/sw/conda1/manage/bin/psconda.sh

psocake unable to override hidden files such as .temp.lst, .temp.stream etc prevents interactive indexing

Note from Cong: mkdir -p tmp needed to batch indexing

**Comment by chuckie82** [comment]
Created s3df branch based on this PR.

**Pull request closed without merging**
